### ISSUE TITLE
I don't think it's working anymore

### ISSUE THREAD

**Issue by xonline** [keyvanarasteh/binance_profit#1]
First of all, thanks for the tool. It sounds like a great addition to use for the Binance Future. 

Altho i don't think it is working at the moment. 
![Screen Shot 2020-04-20 at 3 07 35 am](https://user-images.githubusercontent.com/31034272/79694550-41547680-82b4-11ea-9fdc-99827f16b7e9.png)

As you can see the screenshot here. The position is open, the extension has been allowed to access the website but i didn't/couldn't see any profit box as mentioned in the readme.

**Comment by keyvanarasteh** [comment]
you need to update selectors I used in code.
